/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Dialogue: typeof import('./components/Dialogue.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InputDisplay: typeof import('./components/InputDisplay.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    ThemeMenu: typeof import('./components/ThemeMenu.vue')['default']
  }
}
